[package]
name = "mandel"
version = "0.2.0"
authors = ["Willi Kappler"]

[dependencies]
time = "0.1"
num = "0.1"
clap = "1"
scoped_threadpool = "0.1"
simple_parallel = "0.3"
rayon = {git = "https://github.com/nikomatsakis/rayon.git"}
crossbeam = "0.2"
