[package]
name = "mandel_util"
version = "0.4.0"
authors = ["Willi Kappler, grandor@gmx.de"]
build = "build.rs"

[build-dependencies]
rustc_version = "0.1"

[dependencies]
time = "0.1"
num = "0.1"
clap = "1"
num_cpus = "1.0"

[profile.release]
lto = true
